### PR TITLE
Fix export submenu on touch devices

### LINKED ISSUE #363: File > Export menu does not open on iPadOS
Tested on iPad Pro (10.5-inch) running iPad OS 17.7.3.

Just to be clear, I did have a scene loaded.

### PR DESCRIPTION
**Pull request by willeastcott**
Fixes #363

### CODE REVIEW

File: src/ui/menu-panel.ts [hunk 1]
```diff
@@ -46,6 +46,11 @@ const isString = (value: any) => {
     return !value || typeof value === 'string' || value instanceof String;
 };
 
+// Detect if we're on a touch device
+const isTouchDevice = () => {
+    return 'ontouchstart' in window || navigator.maxTouchPoints > 0;
```
[the remark this answers is not in the document]
Comment (willeastcott) [reply src/ui/menu-panel.ts]: We don't care about IE and very old browsers.

File: src/ui/menu-panel.ts [hunk 2]
```diff
@@ -46,6 +46,11 @@ const isString = (value: any) => {
...
+};
```
Comment (slimbuck) [inline src/ui/menu-panel.ts]: Could do:
```suggestion
const isTouchDevice = 'ontouchstart' in window || navigator.maxTouchPoints > 0;
```

Comment (willeastcott) [reply src/ui/menu-panel.ts]: Done.
